# Generated by Django 2.0.4 on 2018-05-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocatalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
