# Generated by Django 2.0.4 on 2018-05-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocatalogue', '0002_auto_20180523_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='description',
            field=models.TextField(),
        ),
    ]
